version: '3'
services:
  k6:
    image: grafana/k6
  influxdb:
    image: influxdb:1.7
    environment:
      - INFLUXDB_DB=rails_metrics
      - INFLUXDB_USER=${INFLUX_USER-:kjadsuiqwjdiqwoqqqwd}
      - INFLUXDB_USER_PASSWORD=${INFLUX_PASS-:dsgsfgdsfgaddfgdffgdsafgd}
      - INFLUXDB_READ_USER=grafana
      - INFLUXDB_READ_USER_PASSWORD=grafana
    volumes:
      - influxdb-data:/var/lib/influxdb
    ports:
      - 8086:8086
  hoststats:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
  redis:
    image: redis:alpine
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yml
    ports:
      - "3100:3100"
  promtail:
    image: grafana/promtail:latest
    links:
      - loki
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yml
      - rails-logs:/var/log/rails
      - caddy-logs:/var/log/caddy
      - nginx-logs:/var/log/nginx
      # - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
  grafana:
    image: grafana/grafana:latest
    # logging:
    #   driver: loki
      # options:
      #   loki-url: http://host.docker.internal:3100/loki/api/v1/push
      #   loki-relabel-config: |
      #     - action: labelmap
      #       regex: swarm_stack
      #       replacement: namespace
      #     - action: labelmap
      #       regex: swarm_(service)
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    links:
      - prometheus
      - loki
      - promtail
      - influxdb
      - graphite
    ports:
      - "3001:3000"
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "8080"
  caddy:
    image: caddy:alpine
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy-logs:/var/log/caddy
    ports:
      - "8089:80"
      - "8443:443"
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.
      - nginx-logs:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    links:
      - rails
networks:
  internal_network:
    driver: bridge

volumes:
  caddy-logs:
  nginx-logs:
  rails-logs:
  grafana_data:
  influxdb-data:

