version: '3'
services:
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=profana_development
    volumes:
      - postgres:/var/lib/postgresql/data
  caddy:
    volumes:
      - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile
    ports:
      - "8089:80"
  nginx:
    image: nginx:alpine
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/rails_site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8088:80"
    links:
      - rails
  rails:
    deploy:
      replicas: 2
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    labels:
      app: "rails_app"
    volumes:
      - rails-logs:/app/log
    links:
      - db
      - prometheus
      - promtail
      - loki
    build:
      context: rails
      dockerfile: Dockerfile
      target: dev
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/profana_development

volumes:
  postgres:
    driver: local
