services:
  caddy:
    image: caddy:alpine
    networks:
      default: null
    ports:
    - mode: ingress
      target: 80
      published: 80
      protocol: tcp
    - mode: ingress
      target: 443
      published: 443
      protocol: tcp
    volumes:
    - type: bind
      source: /home/rovel/dev/profana/Caddyfile.dev
      target: /etc/caddy/Caddyfile
      bind:
        create_host_path: true
    # deploy:
    #   placement:
    #     constraints:
    #       - node.labels.node_type == lb
  db:
    environment:
      POSTGRES_DB: profana_development
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:11.1
    networks:
      default: null
    volumes:
    - type: volume
      source: postgres
      target: /var/lib/postgresql/data
      volume: {}
  grafana:
    environment:
      ADMIN_PASSWORD: admin
      ADMIN_USER: admin
    image: grafana/grafana:latest
    links:
    - prometheus
    - loki
    - promtail
    networks:
      default: null
    ports:
    - mode: ingress
      target: 3000
      published: 3001
      protocol: tcp
    volumes:
    - type: volume
      source: grafana_data
      target: /var/lib/grafana
      volume: {}
  loki:
    command:
    - -config.file=/etc/loki/local-config.yaml
    image: grafana/loki:2.9.0
    networks:
      default: null
    ports:
    - mode: ingress
      target: 3100
      published: 3100
      protocol: tcp
    volumes:
    - type: bind
      source: /home/rovel/dev/profana/loki-config.yaml
      target: /etc/loki/local-config.yml
      bind:
        create_host_path: true
  prometheus:
    image: prom/prometheus:latest
    networks:
      default: null
    ports:
    - mode: ingress
      target: 9090
      published: 9090
      protocol: tcp
    volumes:
    - type: bind
      source: /home/rovel/dev/profana/prometheus.yaml
      target: /etc/prometheus/prometheus.yaml
      bind:
        create_host_path: true
  promtail:
    command:
    - -config.file=/etc/promtail/config.yml
    image: grafana/promtail:2.9.0
    links:
    - loki
    networks:
      default: null
    volumes:
    - type: bind
      source: /home/rovel/dev/profana/promtail-config.yaml
      target: /etc/promtail/config.yml
      bind:
        create_host_path: true
    - type: volume
      source: rails-logs
      target: /var/log/rails
      volume: {}
  rails_app:
    build:
      context: /home/rovel/dev/profana
      dockerfile: Dockerfile
      target: dev
    deploy:
      replicas: 2
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/profana_development
      RAILS_ENV: development
    labels:
      app: rails_app
    links:
    - db
    - prometheus
    - promtail
    - loki
    networks:
      default: null
    volumes:
    - type: volume
      source: rails-logs
      target: /app/log
      volume: {}
  redis:
    image: redis:alpine
    networks:
      default: null
networks:
  default:
    name: profana_default
volumes:
  caddy_data:
    name: profana_caddy_data
  grafana_data:
    name: profana_grafana_data
  postgres:
    name: profana_postgres
    driver: local
  rails-logs:
    name: profana_rails-logs
