version: '3'
services:
  loki:
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/loki.config.prod.yaml:/etc/loki/local-config.yaml
  rails_app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    environment:
      - RAILS_ENV=production

