server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: rails
    static_configs:
      - targets:
          - localhost
        labels:
          job: rails
          type: web
          __path__: /var/log/rails/*.log   
  - job_name: caddy
    static_configs:
      - targets:
          - localhost
        labels:
          job: caddy
          type: lb
          __path__: /var/log/caddy/*.log
  - job_name: nginx-loki
    pipeline_stages:
    - replace:
        expression: '(?:[0-9]{1,3}\.){3}([0-9]{1,3})'
        replace: '***'
    static_configs:
    - targets:
        - localhost
      labels:
        job: nginx_access_log
        agent: promtail
        __path__: /var/log/nginx/access_json.log
  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          type: lb
          __path__: /var/log/nginx/*.log
      
